# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1000)),
                ('travelstart', models.DateTimeField()),
                ('travelend', models.DateTimeField()),
                ('createdby', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(to='belt.Users')),
            ],
            managers=[
                ('tripmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
